version: "3.8"

services:
  mc-server:
    build: .
    container_name: mc-server
    environment:
      MINECRAFT_PORT: 25565
      MEMORY_MIN: 1G
      MEMORY_MAX: 2G
    ports:
      - "8888:25565"
    volumes:
      - mc-world:/opt/minecraft/world
      - ./mods:/opt/minecraft/mods
    restart: unless-stopped

volumes:
  mc-world:
