services:
  mc-server:
    build: .
    container_name: mc-server
    env_file:
      - .env
    ports:
      - "8888:${SERVER_PORT}"
    volumes:
      - mc-world:/opt/minecraft/world
    restart: unless-stopped

volumes:
  mc-world:
